name = "chittyos-coordination-agent"
main = "ai-enhanced-coordinator.js"
compatibility_date = "2024-09-15"
compatibility_flags = ["nodejs_compat"]

# AI Workers binding for intelligence features
[ai]
binding = "AI"

[durable_objects]
bindings = [
  { name = "CHITTYOS_COORDINATOR", class_name = "AIEnhancedCoordinator" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChittyOSCoordinator"]

[[migrations]]
tag = "v2"
renamed_classes = [
  { from = "ChittyOSCoordinator", to = "AIEnhancedCoordinator" }
]

[vars]
ENVIRONMENT = "production"
AI_ENABLED = "true"

# For production, add these as secrets:
# wrangler secret put NEON_DATABASE_URL
# wrangler secret put NOTION_TOKEN
# wrangler secret put GITHUB_TOKEN